kind: Service
apiVersion: v1
metadata:
  name: "{{ .Values.name }}"
  labels:
  namespace: svetoslavpetrov
spec:
  type: LoadBalancer
  selector:
    app: "{{ .Values.name }}"
  ports:
    - port: 80
      #nodePort: 31500
      protocol: TCP
