kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: svetoslavpetrov
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      #nodePort: 31500
      protocol: TCP
